name: scenova
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/foto1.jpg
    - assets/foto2.jpeg
    - assets/foto3.jpeg
    - assets/foto4.jpeg
    - assets/foto5.jpeg
    - assets/foto6.jpeg
    - assets/foto7.jpeg
    - assets/foto8.jpeg
    - assets/foto9.jpeg
    - assets/foto10.jpeg
    - assets/foto11.jpeg
    - assets/foto12.jpeg
    - assets/foto13.jpg
    - assets/foto14.jpg
    - assets/foto15.jpg
    - assets/foto16.jpeg
    - assets/foto17.jpeg
    - assets/foto18.jpeg
